# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-13 10:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Arrangement',
            fields=[
                ('arrange_id', models.AutoField(primary_key=True, serialize=False)),
                ('arrange_title', models.CharField(max_length=200)),
                ('arrange_cost', models.IntegerField()),
                ('arrange_details', models.CharField(max_length=1000)),
                ('arrange_status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('att_id', models.AutoField(primary_key=True, serialize=False)),
                ('att_date', models.DateField()),
                ('att_status', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Booked_Slot',
            fields=[
                ('booked_id', models.AutoField(primary_key=True, serialize=False)),
                ('booked_date', models.DateField()),
                ('booked_hall', models.CharField(max_length=2)),
                ('booked_slot', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Business_Details',
            fields=[
                ('business_details_id', models.IntegerField(primary_key=True, serialize=False)),
                ('business_logo', models.ImageField(upload_to='')),
                ('business_name', models.CharField(max_length=500)),
                ('business_ownername', models.CharField(max_length=70)),
                ('business_ownername2', models.CharField(max_length=70)),
                ('business_owner_contactno', models.CharField(max_length=20)),
                ('business_owner_contactno2', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=264)),
                ('emp_joindate', models.DateField()),
                ('emp_salary', models.IntegerField()),
                ('emp_status', models.CharField(max_length=30)),
                ('emp_designation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_no', models.IntegerField()),
                ('event_date', models.DateField()),
                ('event_hall', models.CharField(max_length=1)),
                ('event_slot', models.TimeField()),
                ('event_booking_date', models.DateField()),
                ('event_cust_name', models.CharField(max_length=70)),
                ('event_cust_email', models.EmailField(max_length=264)),
                ('event_cust_contactno', models.TextField(max_length=20)),
                ('event_cust_contactno2', models.TextField(max_length=20)),
                ('event_cust_nic', models.TextField(max_length=15)),
                ('event_total_guests', models.IntegerField()),
                ('event_total_amount', models.BigIntegerField()),
                ('event_advance', models.BigIntegerField()),
                ('event_total_expense', models.BigIntegerField()),
                ('event_payments_details', models.TextField(blank=True, null=True)),
                ('event_details', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event_Arrangement',
            fields=[
                ('event_arrangement_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_arrange_cost', models.IntegerField()),
                ('event_arrange_details', models.TextField()),
                ('event_arrangement_arrange_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='realapp.Arrangement')),
                ('event_arrangement_event_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='realapp.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Event_Menu',
            fields=[
                ('event_menu_id', models.AutoField(primary_key=True, serialize=False)),
                ('menu_cost_perhead', models.IntegerField()),
                ('menu_details', models.TextField()),
                ('event_menu_event_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='realapp.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('expense_id', models.AutoField(primary_key=True, serialize=False)),
                ('expense_title', models.CharField(max_length=100)),
                ('expense_date', models.DateField()),
                ('expense_details', models.TextField()),
                ('expense_amount', models.BigIntegerField()),
                ('expense_event_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='realapp.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menu_id', models.AutoField(primary_key=True, serialize=False)),
                ('menu_title', models.CharField(max_length=500)),
                ('menu_cost_perhead', models.IntegerField()),
                ('menu_details', models.TextField()),
                ('menu_status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('salary_id', models.AutoField(primary_key=True, serialize=False)),
                ('salary_month', models.DateField()),
                ('salary_amount_paid', models.IntegerField()),
                ('salary_total_amount', models.IntegerField()),
                ('paid_status', models.CharField(max_length=30)),
                ('salary_remarks', models.CharField(max_length=500)),
                ('salary_emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realapp.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('term_id', models.IntegerField(primary_key=True, serialize=False)),
                ('term_title', models.CharField(max_length=100)),
                ('term_statement', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='event_menu',
            name='event_menu_menu_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='realapp.Menu'),
        ),
        migrations.AddField(
            model_name='booked_slot',
            name='booked_slot_event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realapp.Event'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='att_emp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realapp.Employee'),
        ),
    ]
