# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-15 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='conclude_event',
            field=models.CharField(default=False, max_length=20),
        ),
    ]
