# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-21 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realapp', '0004_event_additional_overall_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='advance',
            field=models.CharField(default=0, max_length=1000),
        ),
        migrations.AddField(
            model_name='salary',
            name='loan',
            field=models.CharField(default=0, max_length=1000),
        ),
    ]
