# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-22 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realapp', '0005_auto_20180320_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_slot',
            field=models.CharField(max_length=20),
        ),
    ]
