# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-23 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realapp', '0006_auto_20180322_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_arrangement',
            name='event_arrange_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
