# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-23 08:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realapp', '0007_event_arrangement_event_arrange_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_Special_Arrangement',
            fields=[
                ('arrange_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_arrange_quantity', models.IntegerField(default=0)),
                ('event_arrange_cost', models.IntegerField()),
                ('event_arrangement_event_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='realapp.Event')),
            ],
        ),
    ]
