# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-23 22:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realapp', '0009_auto_20180323_0148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Special_Arrangement',
            fields=[
                ('special_arrange_id', models.AutoField(primary_key=True, serialize=False)),
                ('special_arrange_title', models.CharField(max_length=200)),
                ('special_arrange_cost', models.IntegerField()),
                ('special_arrange_details', models.CharField(max_length=1000)),
                ('special_arrange_status', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='event_special_arrangement',
            name='special_arrange_id',
        ),
        migrations.AddField(
            model_name='event_special_arrangement',
            name='event_arrange_details',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='event_special_arrangement',
            name='event_arrange_title',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='event_special_arrangement',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event_special_arrangement',
            name='event_special_arrange_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='realapp.Special_Arrangement'),
        ),
    ]
