# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-23 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realapp', '0010_auto_20180323_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event_special_arrangement',
            name='id',
        ),
        migrations.AddField(
            model_name='event_special_arrangement',
            name='event_special_arrangement_id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
