# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-07 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realapp', '0011_auto_20180323_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booked_slot',
            name='booked_slot',
            field=models.CharField(max_length=50),
        ),
    ]
