# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-09 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realapp', '0012_auto_20180406_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='Print',
            fields=[
                ('print_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
